DROP TABLE DMSUTILS_REPOSITORY;
CREATE TABLE DMSUTILS_REPOSITORY
(
    STORE_SERVICE_NAME VARCHAR2(100) NOT NULL,
    REPOSITORY_NAME VARCHAR2(100) NOT NULL,
    PRIMARY KEY (STORE_SERVICE_NAME)
);
DROP TABLE DMSUTILS_METADATA;
CREATE TABLE DMSUTILS_METADATA
(
    OBJECT_CODE VARCHAR2(255) NOT NULL, -- will be the mask name of the object
    OBJECT_TYPE VARCHAR2(50) NOT NULL CHECK (OBJECT_TYPE IN ('FOLDER', 'DOCUMENT')), -- can be 'FOLDER' or 'DOCUMENT'
    OBJECT_CONTEXT VARCHAR2(255) NOT NULL, -- will be the context in wich the document is uploaded
    REPOSITORY_NAME_DST VARCHAR2(100) NOT NULL,
    OPERATION_NAME VARCHAR2(255) NOT NULL, -- can be STORE OR MOVE
    REPOSITORY_NAME_SRC VARCHAR2(100) NOT NULL,
    OBJECT_IDENTIFIER_TEMPLATE_SRC VARCHAR2(1000),
    OBJECT_FOLDER_TEMPLATE VARCHAR2(1000) NULL,
    OBJECT_NAME_TEMPLATE VARCHAR2(255) NULL,
    OBJECT_MASK VARCHAR2(255) NULL,
    OBJECT_VERSIONING VARCHAR2(50) DEFAULT 'NONE' CHECK (OBJECT_VERSIONING IN ('NONE', 'MINOR', 'MAJOR')),  --can be
    OBJECT_PROPERTIES_CONNECTION VARCHAR2(50),
    OBJECT_PROPERTIES_SQL VARCHAR2(4000),
    OBJECT_CREATE_PATH NUMBER(1) NOT NULL CHECK (OBJECT_CREATE_PATH IN (0, 1)),
    OBJECT_PRIORITY NUMBER(8) DEFAULT 1000,
    PRIMARY KEY (OBJECT_CODE, OBJECT_TYPE, OBJECT_CONTEXT, REPOSITORY_NAME_DST, OPERATION_NAME, REPOSITORY_NAME_SRC)
);

DROP TABLE DMSUTILS_GROUP;
CREATE TABLE DMSUTILS_GROUP
(
    GROUP_CODE VARCHAR2(100) NOT NULL,
    OBJECT_CODE VARCHAR2(255) NOT NULL, -- will be the mask name of the object
    OBJECT_TYPE VARCHAR2(50) NOT NULL CHECK (OBJECT_TYPE IN ('FOLDER', 'DOCUMENT')), -- can be 'FOLDER' or 'DOCUMENT'
    OBJECT_CONTEXT VARCHAR2(255) NOT NULL, -- will be the context in wich the document is uploaded
    REPOSITORY_NAME_DST VARCHAR2(100) NOT NULL,
    OPERATION_NAME VARCHAR2(255) NOT NULL, -- can be STORE OR MOVE
    REPOSITORY_NAME_SRC VARCHAR2(100) NOT NULL,
    PRIMARY KEY (GROUP_CODE, OBJECT_CODE, OBJECT_TYPE, OBJECT_CONTEXT, REPOSITORY_NAME_DST, REPOSITORY_NAME_SRC)
);
