CREATE DATABASE DMSUtils
ON PRIMARY
(Name = DMSUtils,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DMSUtils\DMSUtils.mdf'),
FILEGROUP FTFG CONTAINS FILESTREAM
(NAME = DMSUtilsFS,
FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DMSUtils\FS')
LOG ON
(Name = DMSUtilsLog,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DMSUtils\DMSUtils.ldf')
WITH FILESTREAM (NON_TRANSACTED_ACCESS = FULL,
DIRECTORY_NAME = N'DMSUtils');

CREATE TABLE DM_STREAMS AS FILETABLE
  WITH
  (
    FILETABLE_DIRECTORY = 'DMSUtils'
 );

CREATE TABLE DM_OBJECTS
   (
    ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    OBJ_PATH VARCHAR(3000) NOT NULL,
    OBJ_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE M_OBJECT_VERSIONS(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FK_DM_OBJECTS INT NOT NULL,
	FK_DM_STREAMS UNIQUEIDENTIFIER NOT NULL,
	VERSION_LABEL VARCHAR(255),

	CONSTRAINT FK_DM_OBJECT_CONSTR FOREIGN KEY (FK_DM_OBJECTS)
	REFERENCES DM_OBJECTS(ID),
	CONSTRAINT FK_DM_STREAMS_CONSTR FOREIGN KEY (FK_DM_STREAMS)
	REFERENCES DM_STREAMS(STREAM_ID),
);